### ISSUE TITLE
Web developer

### ISSUE THREAD

**Issue by starboy007-debug** [starboy007-debug/Developer#3]
make a portfolio
anyone can contribute

**Comment by kishore007k** [comment]
Hii @starboy007-debug Can you be more specific about what type of portfolio you want. And what are all it should contain?

**Comment by starboy007-debug** [comment]
It should contain the header and footer part and in the middle-left part contain an image and the middle-right part contain some info about yourself

**Comment by kishore007k** [comment]
So you want a portfolio with a  Header, footer, landing page, and an about me section. Is that all? @starboy007-debug

**Comment by starboy007-debug** [comment]
yes

**Comment by kishore007k** [comment]
OK! Can you assign me this issue? So that I can work on it.

**Comment by starboy007-debug** [comment]
Now you can work on it
