### ISSUE TITLE
Game

### ISSUE THREAD

**Issue by starboy007-debug** [starboy007-debug/Developer#4]
make any game with coding skill
anyone can contribute here

**Comment by voidrohit** [comment]
Can you add "hacktober" topic to this repository or add the "hacktoberfest-accepted" label to the PR? So that it will eligible for the Hacktoberfest 2020.

**Comment by starboy007-debug** [comment]
sure

**Comment by voidrohit** [comment]
You should add Hacktoberfest as a topic because the pr is invalid towards Hacktoberfest 2020.
This is the reference how its done: [Updates Rule](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by starboy007-debug** [comment]
Now I have added check it out

**Comment by voidrohit** [comment]
Thank You.

**Comment by Suvechchhaa** [comment]
I want to contribute here by making a game in python!

**Comment by starboy007-debug** [comment]
you can contribute here with any language you like

**Comment by LazybuddyNK** [comment]
Can I submit one now?

**Comment by starboy007-debug** [comment]
yes you can

**Comment by starboy007-debug** [comment]
> Can I submit one now?

yes you can
